import {SelectItem} from "../types/select-item-type";

export const towersStageToSelect: SelectItem[] = [
    {label: 'Этаж 3', value: 3},
    {label: 'Этаж 4', value: 4},
    {label: 'Этаж 5', value: 5},
    {label: 'Этаж 6', value: 6},
    {label: 'Этаж 7', value: 7},
    {label: 'Этаж 8', value: 8},
    {label: 'Этаж 9', value: 9},
    {label: 'Этаж 10', value: 10},
    {label: 'Этаж 11', value: 11},
    {label: 'Этаж 12', value: 12},
    {label: 'Этаж 13', value: 13},
    {label: 'Этаж 14', value: 14},
    {label: 'Этаж 15', value: 15},
    {label: 'Этаж 16', value: 16},
    {label: 'Этаж 17', value: 17},
    {label: 'Этаж 18', value: 18},
    {label: 'Этаж 19', value: 19},
    {label: 'Этаж 20', value: 20},
    {label: 'Этаж 21', value: 21},
    {label: 'Этаж 22', value: 22},
    {label: 'Этаж 23', value: 23},
    {label: 'Этаж 24', value: 24},
    {label: 'Этаж 25', value: 25},
    {label: 'Этаж 26', value: 26},
    {label: 'Этаж 27', value: 27},
]
